pipeline {
    agent any

    environment {
        VENV_DIR = ".venv"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/YourUserName/lesson_31.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                python3 -m venv $VENV_DIR
                source $VENV_DIR/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                source $VENV_DIR/bin/activate
                PYTHONPATH=. pytest --junitxml=results.xml --alluredir=allure-results
                '''
            }
        }

        stage('Publish JUnit results') {
            steps {
                junit 'results.xml'
            }
        }

        stage('Allure Report') {
            steps {
                allure([
                    includeProperties: false,
                    jdk: '',
                    results: [[path: 'allure-results']]
                ])
            }
        }
    }
}
